// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjnkevojcbmlrdytsnth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhqbmtldm9qY2JtbHJkeXRzbnRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1OTI5ODcsImV4cCI6MjA1ODE2ODk4N30.T3TeJfHrr1hFrRpieT7_XDi1iKfSNJzkSK3h1VH51gY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);