
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
<<<<<<< HEAD
    - name: Update browserslist DB
      run: npx update-browserslist-db@latest
      
    - name: Security audit
      run: npm audit --production --audit-level=moderate
      continue-on-error: true
      
=======
>>>>>>> 6c6de67a40eba9778a1efbb3bde2900661421378
    - name: Lint
      run: npm run lint || true
      
    - name: Build project
      run: npm run build
<<<<<<< HEAD
      env:
        NODE_ENV: production
        VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
=======
>>>>>>> 6c6de67a40eba9778a1efbb3bde2900661421378
      
    - name: Run tests
      run: npm test || true
    
<<<<<<< HEAD
    - name: Run security scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        format: 'table'
      continue-on-error: true
      
=======
>>>>>>> 6c6de67a40eba9778a1efbb3bde2900661421378
    - name: Cache build output
      uses: actions/cache@v3
      with:
        path: |
          dist
          node_modules
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-
    
    - name: Deploy to Vercel (only on main branch)
<<<<<<< HEAD
      if: github.ref == 'refs/heads/main' && github.repository == 'FuturoDevJunior/teupaiaqueleausente'
=======
      if: github.ref == 'refs/heads/main'
>>>>>>> 6c6de67a40eba9778a1efbb3bde2900661421378
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        vercel-args: '--prod'
        
    - name: Notify on success
      if: success()
      run: |
        echo "::notice::Build and deployment completed successfully! 🚀"

    - name: Notify on failure
      if: failure()
      run: |
        echo "::error::Build or deployment failed! Please check the logs."
